### PR TITLE
Bundle update.

### PR DESCRIPTION
**Pull request by eugenk**

### CODE REVIEW

**Comment by phyrog** [comment]
rbx does not seem to like the rugged version.

**Comment by eugenk** [comment]
Yes, rbx is quite some pain since a some weeks...

**Comment by phyrog** [comment]
So, do you still want to update rugged? If yes, can you add rbx as allowed to fail to travis (+ `fast_finish`)?

**Comment by eugenk** [comment]
I'm not sure yet. Need to take a closer look.

**Comment by eugenk** [comment]
9c2d11a should fix the Rubinius issues.

**Pull request merged**
